ARG IMAGE_VARIANT=jre-focal
ARG OPENJDK_VERSION=11
ARG PYTHON_VERSION=3.9.12

FROM python:${PYTHON_VERSION}-${IMAGE_VARIANT} AS py3
FROM eclipse-temurin:${OPENJDK_VERSION}-${IMAGE_VARIANT}

COPY --from=py3 / /

ARG PYSPARK_VERSION=3.2.1
RUN pip --no-cache-dir install pyspark==${PYSPARK_VERSION}

ENTRYPOINT ["python"]
