name: Build and Push Docker Image CI

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 1 * *
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        openjdk-version: [11]
        python-version: [3.9.12]
        pyspark-version: [3.2.1]
        image-variant: ['jre-focal']
    
    steps:
      - 
        name: Docker Login
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
            echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
         name: Checkout
         uses: actions/checkout@v2
      -
        name: Build the Docker image
        run: |
          docker build . --file Dockerfile \
            --build-arg OPENJDK_VERSION=${{ matrix.openjdk-version }} \
            --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
            --build-arg PYSPARK_VERSION=${{ matrix.pyspark-version }} \
            --build-arg IMAGE_VARIANT=${{ matrix.image-variant }} \
            --tag ykursadkaya/pyspark:${{ matrix.pyspark-version }}-${{ matrix.image-variant }}
      -
        name: Test PySpark Script
        run: |
          docker run --entrypoint="" -v $(pwd):/repo ykursadkaya/pyspark:${{ matrix.pyspark-version }}-${{ matrix.image-variant }} python /repo/test.py
      -
         name: Docker Push
         if: success()
         run: |
           docker push ykursadkaya/pyspark:${{ matrix.pyspark-version }}-${{ matrix.image-variant }}
      -
        name: Slim Buster Tag
        if: matrix.image-variant == 'slim-buster' && success()
        run: |
          docker tag ykursadkaya/pyspark:${{ matrix.pyspark-version }}-${{ matrix.image-variant }} \
            ykursadkaya/pyspark:${{ matrix.pyspark-version }}
             
          docker push ykursadkaya/pyspark:${{ matrix.pyspark-version }}
